
name: Deploy to Gist



on:
  push:
    branches:
      - main

jobs:

  sync-gist:
    
    runs-on: ubuntu-latest

    
    steps:

      - name: Checkout repository
        uses: actions/checkout@v4


      - name: Sync file to Gist
        uses: exuanbo/actions-deploy-gist@v1.1.4
        with:
            token: ${{ secrets.GIST_TOKEN }}
            gist_id: ${{ secrets.GIST_ID }}
            file_path: 'Activate-BitLocker.ps1'